"""Basic TelemetryFlow SDK usage example.

TelemetryFlow Python SDK - Community Enterprise Observability Platform (CEOP)
Copyright (c) 2024-2026 DevOpsCorner Indonesia. All rights reserved.

Auto-generated by telemetryflow-gen.
"""

import time

from telemetry import init, get_client, SpanKind


def main() -> None:
    """Main function demonstrating SDK usage."""
    # Initialize the SDK
    init()
    client = get_client()
    print("TelemetryFlow SDK initialized!")

    try:
        # Record some metrics
        client.increment_counter(
            "app.requests.total",
            attributes={"endpoint": "/api/users"}
        )
        client.record_gauge("app.active_connections", 42)
        client.record_histogram("app.request.duration", 0.125, unit="s")

        # Emit logs
        client.log_info("Application started", {"version": "${service_version}"})

        # Create a trace span
        with client.span("process_request", SpanKind.SERVER) as span_id:
            # Simulate work
            time.sleep(0.1)
            client.add_span_event(span_id, "checkpoint_reached")

            # Nested operation
            with client.span("database_query", SpanKind.CLIENT) as db_span_id:
                time.sleep(0.05)
                client.add_span_event(db_span_id, "query_executed", {"rows": 10})

        # Log completion
        client.log_info("Request processed successfully")

        # Print status
        status = client.get_status()
        print(f"Status: {status}")

    except Exception as e:
        client.log_error(f"Error: {e}")
        raise


if __name__ == "__main__":
    main()
