"""TelemetryFlow integration module.

TelemetryFlow Python SDK - Community Enterprise Observability Platform (CEOP)
Copyright (c) 2024-2026 DevOpsCorner Indonesia. All rights reserved.

Auto-generated by telemetryflow-gen.
"""

from __future__ import annotations

import atexit
import os
from typing import TYPE_CHECKING

from telemetryflow import TelemetryFlowBuilder
from telemetryflow.application.commands import SpanKind

if TYPE_CHECKING:
    from telemetryflow.client import TelemetryFlowClient

# Global client instance
_client: TelemetryFlowClient | None = None


def init() -> TelemetryFlowClient:
    """Initialize TelemetryFlow SDK.

    Returns:
        TelemetryFlowClient: Initialized client instance.

    Example:
        >>> from telemetry import init, get_client
        >>> init()
        >>> client = get_client()
        >>> client.log_info("Application started")
    """
    global _client

    if _client is not None:
        return _client

    _client = (
        TelemetryFlowBuilder()
        .with_auto_configuration()  # Load from environment variables
        .build()
    )

    _client.initialize()

    # Register shutdown on exit
    atexit.register(shutdown)

    return _client


def get_client() -> TelemetryFlowClient:
    """Get the global TelemetryFlow client.

    Returns:
        TelemetryFlowClient: The initialized client.

    Raises:
        RuntimeError: If SDK is not initialized.
    """
    if _client is None:
        raise RuntimeError("TelemetryFlow SDK not initialized. Call init() first.")
    return _client


def shutdown() -> None:
    """Shutdown TelemetryFlow SDK gracefully."""
    global _client
    if _client is not None:
        _client.shutdown()
        _client = None


# Convenience re-exports
__all__ = [
    "init",
    "get_client",
    "shutdown",
    "SpanKind",
]
