"""${entity_name} Commands.

TelemetryFlow Python SDK - Community Enterprise Observability Platform (CEOP)
Copyright (c) 2024-2026 DevOpsCorner Indonesia. All rights reserved.

Auto-generated by telemetryflow-restapi.
"""

from __future__ import annotations

from dataclasses import dataclass
from uuid import UUID

from ${module_name}.application.command.base import Command


@dataclass
class Create${entity_name}Command(Command):
    """Command to create a new ${entity_name_lower}."""

${field_definitions}


@dataclass
class Update${entity_name}Command(Command):
    """Command to update an existing ${entity_name_lower}."""

    id: UUID
${field_definitions}


@dataclass
class Delete${entity_name}Command(Command):
    """Command to delete a ${entity_name_lower}."""

    id: UUID
