"""${entity_name} DTOs.

TelemetryFlow Python SDK - Community Enterprise Observability Platform (CEOP)
Copyright (c) 2024-2026 DevOpsCorner Indonesia. All rights reserved.

Auto-generated by telemetryflow-restapi.
"""

from __future__ import annotations

from dataclasses import dataclass

from ${module_name}.application.dto.base import BaseDTO


@dataclass
class ${entity_name}DTO(BaseDTO):
    """${entity_name} Data Transfer Object."""

${field_dto}


@dataclass
class Create${entity_name}Request:
    """Request to create ${entity_name_lower}."""

${field_dto}


@dataclass
class Update${entity_name}Request:
    """Request to update ${entity_name_lower}."""

${field_dto}
