"""${entity_name} Entity.

TelemetryFlow Python SDK - Community Enterprise Observability Platform (CEOP)
Copyright (c) 2024-2026 DevOpsCorner Indonesia. All rights reserved.

Auto-generated by telemetryflow-restapi.
"""

from __future__ import annotations

from sqlalchemy import Column
from sqlalchemy.dialects.postgresql import UUID

from ${module_name}.domain.entity.base import BaseEntity


class ${entity_name}(BaseEntity):
    """${entity_name} domain entity."""

    __tablename__ = "${entity_name_plural}"

${field_columns}

    def to_dict(self) -> dict:
        """Convert entity to dictionary."""
        result = super().to_dict()
        # Add entity-specific fields
        return result
