-- ${entity_name} Migration (Up)
-- TelemetryFlow Python SDK - Auto-generated by telemetryflow-restapi

CREATE TABLE IF NOT EXISTS ${entity_name_plural} (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
    -- Add entity-specific columns here
);

CREATE INDEX IF NOT EXISTS idx_${entity_name_plural}_created_at ON ${entity_name_plural}(created_at);
