"""${entity_name} Queries.

TelemetryFlow Python SDK - Community Enterprise Observability Platform (CEOP)
Copyright (c) 2024-2026 DevOpsCorner Indonesia. All rights reserved.

Auto-generated by telemetryflow-restapi.
"""

from __future__ import annotations

from dataclasses import dataclass
from uuid import UUID

from ${module_name}.application.query.base import Query, PaginatedQuery


@dataclass
class Get${entity_name}ByIdQuery(Query):
    """Query to get ${entity_name_lower} by ID."""

    id: UUID


@dataclass
class List${entity_name_plural}Query(PaginatedQuery):
    """Query to list all ${entity_name_plural}."""

    pass
