"""${entity_name} Repository Interface.

TelemetryFlow Python SDK - Community Enterprise Observability Platform (CEOP)
Copyright (c) 2024-2026 DevOpsCorner Indonesia. All rights reserved.

Auto-generated by telemetryflow-restapi.
"""

from __future__ import annotations

from abc import abstractmethod

from ${module_name}.domain.entity.${entity_name_lower} import ${entity_name}
from ${module_name}.domain.repository.base import BaseRepository


class ${entity_name}Repository(BaseRepository[${entity_name}]):
    """${entity_name} repository interface."""

    @abstractmethod
    def find_by_id(self, id) -> ${entity_name} | None:
        """Find ${entity_name_lower} by ID."""
        pass

    @abstractmethod
    def find_all(self, limit: int = 100, offset: int = 0) -> list[${entity_name}]:
        """Find all ${entity_name_plural}."""
        pass

    @abstractmethod
    def save(self, entity: ${entity_name}) -> ${entity_name}:
        """Save ${entity_name_lower}."""
        pass

    @abstractmethod
    def delete(self, id) -> bool:
        """Delete ${entity_name_lower} by ID."""
        pass
