"""Route Registration.

TelemetryFlow Python SDK - Community Enterprise Observability Platform (CEOP)
Copyright (c) 2024-2026 DevOpsCorner Indonesia. All rights reserved.

Auto-generated by telemetryflow-restapi.
"""

from __future__ import annotations

from flask import Flask

from ${module_name}.infrastructure.http.handlers.health import health_bp


def register_routes(app: Flask) -> None:
    """Register all application routes.

    Args:
        app: Flask application.
    """
    # Health check
    app.register_blueprint(health_bp, url_prefix="/api/v1")

    # Add entity routes here as they are generated
    # Example: app.register_blueprint(user_bp, url_prefix="/api/v1")
