# =============================================================================
# ${project_name} Configuration
# =============================================================================
#
# TelemetryFlow Python SDK - Community Enterprise Observability Platform (CEOP)
# Copyright (c) 2024-2026 DevOpsCorner Indonesia. All rights reserved.
#
# Auto-generated by telemetryflow-restapi.
#
# =============================================================================

# Service Configuration
${env_prefix}_SERVICE_NAME=${service_name}
${env_prefix}_SERVICE_VERSION=${service_version}
${env_prefix}_ENVIRONMENT=${environment}

# Server Configuration
${env_prefix}_HOST=0.0.0.0
${env_prefix}_PORT=${server_port}
${env_prefix}_DEBUG=false

# Database Configuration
${env_prefix}_DB_DRIVER=${db_driver}
${env_prefix}_DB_HOST=${db_host}
${env_prefix}_DB_PORT=${db_port}
${env_prefix}_DB_NAME=${db_name}
${env_prefix}_DB_USER=${db_user}
${env_prefix}_DB_PASSWORD=your_password_here

# Security Configuration
${env_prefix}_SECRET_KEY=change-me-in-production-use-secure-random-string
${env_prefix}_JWT_SECRET_KEY=change-me-in-production-use-secure-random-string
${env_prefix}_JWT_EXPIRES=3600

# TelemetryFlow Configuration
${env_prefix}_TELEMETRY_ENABLED=true
TELEMETRYFLOW_API_KEY_ID=tfk_your_key_id
TELEMETRYFLOW_API_KEY_SECRET=tfs_your_key_secret
TELEMETRYFLOW_ENDPOINT=api.telemetryflow.id:4317
TELEMETRYFLOW_SERVICE_NAME=${service_name}
TELEMETRYFLOW_SERVICE_VERSION=${service_version}
TELEMETRYFLOW_ENVIRONMENT=${environment}

# Feature Flags
${env_prefix}_CORS_ENABLED=true
${env_prefix}_RATE_LIMIT_ENABLED=true
${env_prefix}_SWAGGER_ENABLED=true
