# =============================================================================
# ${project_name} Requirements
# =============================================================================
#
# TelemetryFlow Python SDK - Community Enterprise Observability Platform (CEOP)
# Copyright (c) 2024-2026 DevOpsCorner Indonesia. All rights reserved.
#
# Auto-generated by telemetryflow-restapi.
#
# =============================================================================

# Web Framework
flask>=3.0.0
flask-cors>=4.0.0
flask-limiter>=3.5.0
flask-jwt-extended>=4.6.0
flask-sqlalchemy>=3.1.0
flasgger>=0.9.7

# Database
sqlalchemy>=2.0.0
alembic>=1.13.0
psycopg2-binary>=2.9.9

# Validation
pydantic>=2.5.0

# Configuration
python-dotenv>=1.0.0

# TelemetryFlow (Observability)
telemetryflow-python-sdk>=1.1.0

# Production Server
gunicorn>=21.0.0
